{
 "title": "Dashboard 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Timer: Advance Ledger",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.advanceLedger.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.acceptLedger_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Accept Ledger ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.acceptLedger.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.acceptLedger_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Trusted Validation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.trustedValidation.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.trustedValidation_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Untrusted Proposal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.untrustedProposal.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.untrustedProposal_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Ledger Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.ledgerData.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.ledgerData_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Fetch Transaction Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.fetchTxnData.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.fetchTxnData_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Ledger Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.ledgerRequest.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.ledgerRequest_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.transaction.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.transaction_q.mean"
    }
   ]
  },
  {
   "title": "Ledger Fetches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.mayur_validator.ledger_fetches"
    }
   ]
  },
  {
   "title": "Timer: Trusted Proposal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.trustedProposal.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.trustedProposal_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Write Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.writeObjects.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.writeObjects_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Heart Beat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.heartbeat.mean"
    },
    {
     "target": "stats.timers.mayur_validator.jobq.heartbeat_q.mean"
    }
   ]
  },
  {
   "title": "Timer: Write Ahead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.writeAhead.count"
    }
   ]
  },
  {
   "title": "Timer: Sweep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.sweep.count"
    }
   ]
  },
  {
   "title": "Timer: Batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.mayur_validator.jobq.batch.count"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.mayur_validator.jobq.job_count"
    }
   ]
  },
  {
   "title": "Full Below Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.mayur_validator.full_below.hit_rate"
    }
   ]
  },
  {
   "title": "Full Below Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.mayur_validator.full_below.size"
    }
   ]
  }
 ]
}